---
# tasks file for vmwaretools/Suse

- name: Install vmware-tools repository for SLES 11. 
  zypper: name={{ vmwaretools_yum_server }}{{ vmwaretools_yum_path }}/esx/{{ vmwaretools_tools_version }}/repos/vmware-tools-repo-SLES{{ ansible_distribution_major_version }}.{{ ansible_distribution_release }}-{{ vmwaretools_repo_version }}.sles{{ ansible_distribution_major_version }}.{{ ansible_architecture }}.rpm state=present
  when: ansible_distribution_major_version|int == 11

- name: Install vmware-tools.
  zypper: name=vmware-tools-esx state=present disable_gpg_check=yes
  when: ansible_distribution_major_version|int == 11

- name: Installing Open VMware Tools (open-vm-tools) for SLES12 and higher or OpenSuse.
  zypper: name=open-vm-tools state=installed
  when: ansible_distribution_major_version|int != 11
